version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "portal-parceiro-backend-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16s0xrgyf24d2"
s3_prefix = "portal-parceiro-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM CAPABILITY_IAM"
parameter_overrides = "Project=\"Pontte\" Environment=\"test\" CognitoUserPoolArn=\"arn:aws:cognito-idp:us-east-1:848638426587:userpool/us-east-1_6C2LVMjB2\""
image_repositories = []
