AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >-
  Funcoes relacionadas ao Registro do usuário no portal do parceiro

Parameters:
  StageName:
    Description: nome do estagio na URL quando em producao
    Type: String
    Default: v1

  Project:
    Description: nome do Project
    Type: String
    Default: Pontte

  Environment:
    Description: ambiente de execucao do servico
    Type: String
    AllowedValues:
      - dev
      - staging
      - prod

  CommonLayer:
    Description: common resources for lambdas
    Type: String

  LibrariesLayer:
    Description: common libraries for lambdas
    Type: String

Globals:
  Function:
    Layers:
      - !Ref CommonLayer
      - !Ref LibrariesLayer
    Runtime: python3.8
    MemorySize: 1024
    Timeout: 120
    Environment:
      Variables:
        ENV: !Ref Environment
        PROJECT: !Ref Project
    Tags:
      Project: !Ref Project
      Environment: !Ref Environment

Resources:
  PosConfirmationFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Project}-PosConfirmationFn-${Environment}"
      Description: Invoked automatically after a user has confirmed their account
      CodeUri: pos_confirmation
      Handler: app.lambda_handler
      Tracing: Active
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Sub "{{resolve:ssm:/userInvite/${Environment}:1}}"
        - Statement:
            - Sid: "CognitoAdminAddUserToGroupPolicy"
              Effect: Allow
              Action:
                - cognito-idp:AdminAddUserToGroup
              Resource: !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/{{resolve:ssm:/portalparceirofrontend/cognito/${Environment}:1}}"
        - SSMParameterReadPolicy:
            ParameterName: !Sub "userInvite/${Environment}"
        - SSMParameterReadPolicy:
            ParameterName: !Sub "portalparceirofrontend/cognito/${Environment}"
        - SSMParameterReadPolicy:
            ParameterName: !Sub "portalparceirofrontend/api/${Environment}"
        - SSMParameterReadPolicy:
            ParameterName: !Sub "portalparceirofrontend/apikey/${Environment}"
