AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >-
  Funcoes relacionadas a Simuação do cliente no portal do parceiro
Parameters:
  StageName:
    Description: nome do estagio na URL quando em producao
    Type: String
    Default: v1

  Project:
    Description: nome do Project
    Type: String
    Default: Pontte

  Environment:
    Description: ambiente de execucao do servico
    Type: String
    AllowedValues:
      - test
      - dev
      - staging
      - prod

  CommonLayer:
    Description: common resources for lambdas
    Type: String

  LibrariesLayer:
    Description: common libraries for lambdas
    Type: String

  APIDomainName:
    Description: nome da API
    Type: String

  BasePath:
    Description: base path da API
    Type: String
    Default: WhiteLabel

  CognitoUserPoolArn:
    Description: ARN do User Pool do Cognito
    Type: String

Conditions:
  Prod: !Equals [ !Ref Environment, prod ]

Globals:
  Function:
    Layers:
      - !Ref CommonLayer
      - !Ref LibrariesLayer
    Runtime: python3.8
    MemorySize: 1024
    Timeout: 120
    Environment:
      Variables:
        ENV: !Ref Environment
        PROJECT: !Ref Project
        APP_SYNC_API_ID: !Sub "{{resolve:ssm:/portalparceirofrontend/appsync/id/${Environment}:1}}"
    Tags:
      Project: !Ref Project
      Environment: !Ref Environment
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'Authorization,Content-Type,If-Match'"
      AllowOrigin: "'*'"

Resources:
  WhiteLabelApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${Project}-WhiteLabelApi-${Environment}"
      StageName: !If [ Prod, !Ref StageName, !Ref Environment ]
      GatewayResponses:
        DEFAULT_4xx:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Headers: "'*'"
              Access-Control-Allow-Origin: "'*'"

        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Headers: "'*'"
              Access-Control-Allow-Origin: "'*'"

        EXPIRED_TOKEN:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Headers: "'*'"
              Access-Control-Allow-Origin: "'*'"

  WhiteLabelMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref BasePath
      DomainName: !Ref APIDomainName
      RestApiId: !Ref WhiteLabelApi
      Stage: !Ref WhiteLabelApi.Stage

  GetAllWhiteLabelFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Project}-GetAllWhiteLabelFn-${Environment}"
      Description: function that get all whitelabels
      CodeUri: GetAll
      Handler: app.lambda_handler
      Tracing: Active
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: "/v1/whitelabel"
            Method: GET
            RestApiId: !Ref WhiteLabelApi
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Sub "portalparceirofrontend/api/${Environment}"
        - DynamoDBReadPolicy:
            TableName: !Sub "WhiteLabel-{{resolve:ssm:/portalparceirofrontend/appsync/id/${Environment}:1}}-${Environment}"
